#!/usr/bin/env python3
"""Extract every MUST/MUST NOT line from the core spec with its
section anchor — the D-104 audit's raw corpus. Deterministic output;
CI runs it and diffs against the committed corpus so a spec edit
that adds or moves a requirement fails loudly until the audit
(conformance/MUST-AUDIT.md) is updated to match.
"""
import re
import sys

SPEC = 'spec/MLP-Core-Specification-0.1-draft-03.md'
OUT = 'conformance/must-corpus.txt'

def main():
    lines = open(SPEC).read().split('\n')
    section = ''
    rows = []
    for line in lines:
        m = re.match(r'^#{2,4}\s+((?:[\d.]+|Annex [A-Z])[^#]*)', line)
        if m:
            section = m.group(1).strip()
        if 'MUST' in line:
            text = re.sub(r'\s+', ' ', line.strip().lstrip('|>- ').strip())
            n = len(re.findall(r'MUST(?: NOT)?', line))
            rows.append((section, n, text))
    total = sum(n for _, n, _ in rows)
    with open(OUT, 'w') as f:
        f.write(f"# {len(rows)} lines, {total} MUST/MUST NOT occurrences — generated by audit-musts.py; do not edit\n")
        for i, (sec, n, text) in enumerate(rows, 1):
            f.write(f"M{i:03d} [{sec}] ({n}) {text}\n")
    print(f"must-corpus: {len(rows)} lines, {total} occurrences")
    return 0

if __name__ == '__main__':
    sys.exit(main())
